### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by zedle** [cubiclesoft/php-winpefile#3]
Noticed there is no license file... What is this licensed as?

**Comment by zedle** [comment]
Found this in the README header, really should add a license file though!

**Comment by cubiclesoft** [comment]
The PE artifact library repo (linked from this repo) is really the only repo I have that lacks a license statement since one can't be applied.  That repo is pretty clear about that fact.  This repo has the standard CubicleSoft dual-license option as you noted.  There's little reason to repeat common, well-recognized licenses ad nauseum.
