### ISSUE TITLE
Out of bound access in checksum update with malformed header

### ISSUE THREAD

**Issue by nicolaslegland** [cubiclesoft/php-winpefile#9]
I came across [files](https://github.com/cubiclesoft/php-winpefile/files/10943281/error.7z.gz) that broke [win_pe_file.php at line 2874](../tree/b8b6767c9b4b3abe26161f3e0f2b0c326abe0cfc/support/win_pe_file.php#L2874) with `unpack(): Type v: not enough input, need 2, have 0.`. This is likely because their DOS header advertise the wrong page count or last page size, which are used [at line 1831](../tree/b8b6767c9b4b3abe26161f3e0f2b0c326abe0cfc/support/win_pe_file.php#L1831) to determine checksumed range size. They probably aren't to be trusted, but it shouldn't lead to an out of bound access.

**Comment by cubiclesoft** [comment]
This should be fixed now.  The other calculations just use the size of the data while this one can run out of bounds.  PHP can't formally crash when going out of bounds - it'll mostly just display warnings about the issue.

This code probably crashes with malformed DOS headers:

https://jeffpar.github.io/kbarchive/kb/071/Q71971/

The checksum calculation is done based on that original knowledgebase article.  As we've established/discovered though, it seems like the checksum algorithm itself isn't correct anyway for NE files.  So the bounds check is kind of moot until we figure out what the correct algorithm should be (if there even is one).

I don't think I've really tried to validate the checksum logic for NE files because my sample size was far too small and 16-bit programs won't run on modern hardware anyway due to 64-bit hardware and OSes not supporting 16-bit programs.  Not saying we shouldn't try to make this work but the audience and use-case for the NE section of this library is rather limited.
